- name: Downloading the latest version of corkscrew
  unarchive:
    src: "https://github.com/bryanpkc/corkscrew/archive/v{{ corkscrew_git_version }}.tar.gz"
    dest: /opt/
    remote_src: yes
  become: yes

- name: Autoreconf corkscrew
  become: yes
  shell: autoreconf --install
  args:
    chdir: "/opt/corkscrew-{{ corkscrew_git_version }}"

- name: Configuring corkscrew
  become: yes
  shell: ./configure --prefix={{ prefix }}
  args:
    chdir: "/opt/corkscrew-{{ corkscrew_git_version }}"

- name: Making corkscrew
  become: yes
  make:
    chdir: "/opt/corkscrew-{{ corkscrew_git_version }}"

- name: Installing corkscrew
  become: yes
  make: 
    chdir: "/opt/corkscrew-{{ corkscrew_git_version }}"
    target: install