- name: Uninstalling corkscrew
  make:
    target: uninstall
    chdir: "/opt/corkscrew-{{ corkscrew_local_version }}"
  become: yes

- name: Removing source folder
  become: true
  file:
    path: "/opt/corkscrew-{{ corkscrew_local_version }}"
    state: absent